### ISSUE TITLE
How to get mlstm_ns.pt

### ISSUE THREAD

**Issue by ghost** [guillitte/pytorch-sentiment-neuron#2]
Hi Stéphane @guillitte , 

thanks for sharing this, its really very interesting :+1: 

I don't know where to get the file, `mlstm_ns.pt`?

On the front of the repo it says,

> Click on release to get model file mlstm_ns.pt

Where is release?

Thanks for your help,

Ajay :)

**Comment by guillitte** [comment]
In the toolbar of the first project page (<>code), you should have the labels 

 10 commits   1 branch    1 release  1 contributor

Just click on 1 release

**Comment by ghost** [comment]
Thank you very much :+1:
