### ISSUE TITLE
Strange output when converting to cpu

### ISSUE THREAD

**Issue by ghost** [guillitte/pytorch-sentiment-neuron#3]
Hi,

I converted the model to run on `cpu` using, 

```
checkpoint = torch.load(opt.load_model)
embed = checkpoint['embed']
rnn = checkpoint['rnn']

embed = embed.cpu()
rnn = rnn.cpu()
```

because I'm interested in running unsupervised trained networks on low resource hardware. When I sample the model with command,

`python visualize.py -seq_length 1000 -load_model mlstm_ns.pt -temperature 0.4 -neuron 2388 -init "I couldn't figure out"`

The sentiment is not consistent,

![sentiment_sampling](https://cloud.githubusercontent.com/assets/10279780/25780093/f40f23ca-331a-11e7-8172-fd115042d5bc.png)

Have you got any ideas how I could try to fix it please? I'd like to get the model to run on the `cpu` somehow?

Thanks a lot :+1:

**Comment by guillitte** [comment]
I added the file convert_to_cpu.py to make the conversion.

Then, using for instance the command : 

`python visualize.py -seq_length 1000 -load_model mlstm_ns.pt.cpu -temperature 0.4 -neuron 2388 -overwrite -.5 -init "I didn't like it"`

I got no problem.

**Comment by ghost** [comment]
Thanks a lot - and sorry for the very late reply :+1:

**Comment by goodlux** [comment]
I converted the file using convert_to_cpu.py, and ran the command 

`python visualize.py -seq_length 1000 -load_model mlstm_ns.pt.cpu -temperature 0.4 -neuron 2388 -overwrite -.5 -init "I didn't like it"`

It still looks the same. Is it supposed to produce heatmap text like page 5 of this paper? 

https://arxiv.org/pdf/1704.01444.pdf

Not sure what to expect from visualize.py.


Thanks!
